### ISSUE TITLE
Deploying to Cloud Foundry

### ISSUE THREAD

**Issue by ajcs3** [rabbitmq/rabbitmq-jms-boot-demo#2]
How can we test this sample in cloud foundry?

**Comment by michaelklishin** [comment]
Please post your questions to rabbitmq-users. This demo project doesn't have a CF application manifest but since it is so small and uses Spring Boot, it should be easy enough to produce an uberjar (see README) and [follow Spring Boot Cloud Foundry deployment guide](https://docs.spring.io/spring-boot/docs/current/reference/html/cloud-deployment.html) from there.
